version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=58005800
      - DB_NAME=proyecto
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mysql:5.7
    platform: linux/amd64 # Especifica la plataforma para MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 58005800
      MYSQL_DATABASE: proyecto
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
